//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TTMS.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public enum Status
    {
        Initiated, NotAssigned, Assigned, Inprogress, AboutToFinish, Completed
    }
    public partial class Work
    {
        [Key]
        public int PK_Work { get; set; }
        public int FK_WorkType { get; set; }
        public int FK_WorkPriority { get; set; }
        public string WorkTitle { get; set; }
        public string WorkDescr { get; set; }
        public System.DateTime CreationDate { get; set; }
        public Nullable<System.DateTime> Deadline { get; set; }
        [DisplayFormat(NullDisplayText = "Initiated")]
        public Status? Status { get; set; }
        public virtual WorkPriority WorkPriority { get; set; }
        public virtual WorkType WorkType { get; set; }
    }
}
