// <auto-generated />
namespace TTMS.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class WorkModelChanged551114 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(WorkModelChanged551114));
        
        string IMigrationMetadata.Id
        {
            get { return "201705051618101_Work-Model-Changed-5511-14"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
