// <auto-generated />
namespace TTMS.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class WorkModelChanged0505 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(WorkModelChanged0505));
        
        string IMigrationMetadata.Id
        {
            get { return "201705051448302_Work-Model-Changed-05-05"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
