// <auto-generated />
namespace TTMS.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _41117worklogadded : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_41117worklogadded));
        
        string IMigrationMetadata.Id
        {
            get { return "201704112232191_41117-worklog-added"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
