// <auto-generated />
namespace TTMS.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class new4717 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(new4717));
        
        string IMigrationMetadata.Id
        {
            get { return "201704080038541_new4717"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
